const lawData = [
  {
    id:"1",
    category:"Xây dựng",
    sokyhieu:"135/2025/QH15",
    ngaybanhanh:"10/12/2025",
    ngayhieuluc:"01/7/2026",
    loaivanban:"Luật",
    coquanbanhanh:"Quốc hội",
    nguoiky:"Trần Thanh Mẫn",
    trichyeu:"Luật Xây dựng",
    link:"https://vanban.chinhphu.vn/?pageid=27160&docid=216514&classid=1&orggroupid=1"
  },
  {
    id:"2",
    category:"Tài sản công",
    sokyhieu:"15/2017/QH14",
    ngaybanhanh:"21/6/2017",
    ngayhieuluc:"01/01/2018",
    loaivanban:"Luật",
    coquanbanhanh:"Quốc hội",
    nguoiky:"Nguyễn Thị Kim Ngân",
    trichyeu:"Luật quản lý, sử dụng tài sản công",
    link:"https://vanban.chinhphu.vn/default.aspx?pageid=27160&docid=190302"
  },
  {
    id:"3",
    category:"Tài chính",
    sokyhieu:"22/2023/QH15",
    ngaybanhanh:"23/6/2023",
    ngayhieuluc:"01/01/2024",
    loaivanban:"Luật",
    coquanbanhanh:"Quốc hội",
    nguoiky:"Vương Đình Huệ",
    trichyeu:"Luật Đấu thầu",
    link:"https://vanban.chinhphu.vn/?pageid=27160&docid=208419"
  },
  {
    id:"4",
    category:"Đất đai - Nhà ở",
    sokyhieu:"27/2023/QH15",
    ngaybanhanh:"27/11/2023",
    ngayhieuluc:"01/01/2025",
    loaivanban:"Luật",
    coquanbanhanh:"Quốc hội",
    nguoiky:"Vương Đình Huệ",
    trichyeu:"Luật Nhà ở",
    link:"https://vanban.chinhphu.vn/?pageid=27160&docid=209627"
  },
  {
    id:"5",
    category:"Xây dựng",
    sokyhieu:"50/2014/QH13",
    ngaybanhanh:"18/6/2014",
    ngayhieuluc:"01/01/2015",
    loaivanban:"Luật",
    coquanbanhanh:"Quốc hội",
    nguoiky:"Nguyễn Sinh Hùng",
    trichyeu:"Luật Xây dựng",
    link:"https://vanban.chinhphu.vn/default.aspx?pageid=27160&docid=175348"
  },
  {
    id:"6",
    category:"PCCC",
    sokyhieu:"55/2024/QH15",
    ngaybanhanh:"29/11/2024",
    ngayhieuluc:"01/7/2025",
    loaivanban:"Luật",
    coquanbanhanh:"Quốc hội",
    nguoiky:"Trần Thanh Mẫn",
    trichyeu:"Luật Phòng cháy, chữa cháy và cứu nạn, cứu hộ",
    link:"https://vanban.chinhphu.vn/?pageid=27160&docid=212483"
  },
  {
    id:"7",
    category:"Xây dựng",
    sokyhieu:"62/2020/QH14",
    ngaybanhanh:"17/6/2020",
    ngayhieuluc:"01/01/2021",
    loaivanban:"Luật",
    coquanbanhanh:"Quốc hội",
    nguoiky:"Nguyễn Thị Kim Ngân",
    trichyeu:"Luật sửa đổi, bổ sung một số điều của Luật Xây dựng",
    link:"https://vanban.chinhphu.vn/?pageid=27160&docid=200450"
  },
  {
    id:"8",
    category:"Ngân sách NN",
    sokyhieu:"89/2025/QH15",
    ngaybanhanh:"25/6/2025",
    ngayhieuluc:"01/01/2026",
    loaivanban:"Luật",
    coquanbanhanh:"Quốc hội",
    nguoiky:"Trần Thanh Mẫn",
    trichyeu:"Luật Ngân sách nhà nước",
    link:"https://chinhphu.vn/?pageid=27160&docid=214601&classid=1&orggroupid=1"
  },
  {
    id:"9",
    category:"Dân sự",
    sokyhieu:"91/2015/QH13",
    ngaybanhanh:"24/11/2015",
    ngayhieuluc:"01/01/2017",
    loaivanban:"Luật",
    coquanbanhanh:"Quốc hội",
    nguoiky:"Nguyễn Sinh Hùng",
    trichyeu:"Bộ Luật Dân sự",
    link:"https://vanban.chinhphu.vn/default.aspx?pageid=27160&docid=183188"
  },
  {
    id:"10",
    category:"Tài chính",
    sokyhieu:"57/2024/QH15",
    ngaybanhanh:"29/11/2024",
    ngayhieuluc:"15/01/2025",
    loaivanban:"Luật",
    coquanbanhanh:"Quốc hội",
    nguoiky:"Trần Thanh Mẫn",
    trichyeu:"Luật sửa đổi, bổ sung một số điều của Luật Quy hoạch, Luật Đầu tư, Luật Đầu tư theo phương thức đối tác công tư và Luật Đấu thầu",
    link:"https://vanban.chinhphu.vn/?pageid=27160&docid=212485"
  },
  {
    id:"11",
    category:"Tài chính",
    sokyhieu:"90/2025/QH15",
    ngaybanhanh:"25/6/2025",
    ngayhieuluc:"01/7/2025",
    loaivanban:"Luật",
    coquanbanhanh:"Quốc hội",
    nguoiky:"Trần Thanh Mẫn",
    trichyeu:"Luật sửa đổi, bổ sung một số điều của Luật Đấu thầu, Luật Đầu tư theo phương thức đối tác công tư, Luật Hải quan, Luật Thuế giá trị gia tăng, Luật Thuế xuất khẩu, thuế nhập khẩu, Luật Đầu tư, Luật Đầu tư công, Luật Quản lý, sử dụng tài sản công",
    link:"https://vanban.chinhphu.vn/?pageid=27160&docid=214558"
  },
  {
    id:"12",
    category:"Xây dựng",
    sokyhieu:"06/2021/NĐ-CP",
    ngaybanhanh:"26/01/2021",
    ngayhieuluc:"26/01/2021",
    loaivanban:"Nghị định",
    coquanbanhanh:"Chính phủ",
    nguoiky:"Nguyễn Xuân Phúc",
    trichyeu:"quy định chi tiết một số nội dung về quản lý chất lượng, thi công xây dựng và bảo trì công trình xây dựng",
    link:"https://vanban.chinhphu.vn/?pageid=27160&docid=202585"
  },
  {
    id:"13",
    category:"Xây dựng",
    sokyhieu:"10/2021/NĐ-CP",
    ngaybanhanh:"09/02/2021",
    ngayhieuluc:"09/02/2021",
    loaivanban:"Nghị định",
    coquanbanhanh:"Chính phủ",
    nguoiky:"Nguyễn Xuân Phúc",
    trichyeu:"về quản lý chi phí đầu tư xây dựng",
    link:"https://vanban.chinhphu.vn/default.aspx?pageid=27160&docid=202663"
  },
  {
    id:"14",
    category:"Tài chính",
    sokyhieu:"104/2026/NĐ-CP",
    ngaybanhanh:"31/3/2026",
    ngayhieuluc:"31/3/2026",
    loaivanban:"Nghị định",
    coquanbanhanh:"Chính phủ",
    nguoiky:"Hồ Đức Phớc",
    trichyeu:"quy định việc lập dự toán, quản lý, sử dụng và quyết toán chi thường xuyên để thực hiện các nhiệm vụ quy định tại Điều 40 Luật Ngân sách nhà nước",
    link:"https://vanban.chinhphu.vn/?pageid=27160&docid=217644&classid=1"
  },
  {
    id:"15",
    category:"PCCC",
    sokyhieu:"105/2025/NĐ-CP",
    ngaybanhanh:"15/5/2025",
    ngayhieuluc:"01/7/2025",
    loaivanban:"Nghị định",
    coquanbanhanh:"Chính phủ",
    nguoiky:"Phạm Minh Chính",
    trichyeu:"quy định chi tiết một số điều và biện pháp thi hành Luật Phòng cháy, chữa cháy và cứu nạn, cứu hộ",
    link:"https://vanban.chinhphu.vn/?pageid=27160&docid=213702"
  },
  {
    id:"16",
    category:"Xây dựng",
    sokyhieu:"119/2025/NĐ-CP",
    ngaybanhanh:"09/6/2025",
    ngayhieuluc:"01/8/2025",
    loaivanban:"Nghị định",
    coquanbanhanh:"Chính phủ",
    nguoiky:"Trần Hồng Hà",
    trichyeu:"sửa đổi, bổ sung một số điều của Nghị định số 06/2022/NĐ-CP ngày 07 tháng 01 năm 2022 của Chính phủ quy định giảm nhẹ phát thải khí nhà kính và bảo vệ tầng ô-dôn",
    link:"https://vanban.chinhphu.vn/?pageid=27160&docid=213875"
  },
  {
    id:"17",
    category:"Xây dựng",
    sokyhieu:"14/2026/NĐ-CP",
    ngaybanhanh:"13/01/2026",
    ngayhieuluc:"15/01/2026",
    loaivanban:"Nghị định",
    coquanbanhanh:"Chính phủ",
    nguoiky:"Trần Hồng Hà",
    trichyeu:"sửa đổi, bổ sung một số điều của các Nghị định để cắt giảm, đơn giản hóa thủ tục hành chính liên quan đến hoạt động sản xuất, kinh doanh thuộc phạm vi quản lý của Bộ Xây dựng",
    link:"https://vanban.chinhphu.vn/?pageid=27160&docid=216631"
  },
  {
    id:"18",
    category:"Xây dựng",
    sokyhieu:"175/2024/NĐ-CP",
    ngaybanhanh:"30/12/2024",
    ngayhieuluc:"30/12/2024",
    loaivanban:"Nghị định",
    coquanbanhanh:"Chính phủ",
    nguoiky:"Trần Hồng Hà",
    trichyeu:"quy định chi tiết một số điều và biện pháp thi hành Luật Xây dựng về quản lý hoạt động xây dựng",
    link:"https://vanban.chinhphu.vn/?pageid=27160&docid=212166"
  },
  {
    id:"19",
    category:"Xây dựng",
    sokyhieu:"20/2022/NĐ-CP",
    ngaybanhanh:"10/3/2022",
    ngayhieuluc:"01/7/2022",
    loaivanban:"Nghị định",
    coquanbanhanh:"Chính phủ",
    nguoiky:"Lê Minh Khái",
    trichyeu:"sửa đổi, bổ sung một số điều của Nghị định số 119/2015/NĐ-CP ngày 13 tháng 11 năm 2015 của Chính phủ quy định bảo hiểm bắt buộc trong hoạt động đầu tư xây dựng",
    link:"https://vanban.chinhphu.vn/?pageid=27160&docid=205455"
  },
  {
    id:"20",
    category:"Tài chính",
    sokyhieu:"214/2025/NĐ-CP",
    ngaybanhanh:"04/8/2025",
    ngayhieuluc:"04/8/2025",
    loaivanban:"Nghị định",
    coquanbanhanh:"Chính phủ",
    nguoiky:"Trần Hồng Hà",
    trichyeu:"quy định chi tiết một số điều và biện pháp thi hành Luật Đấu thầu về lựa chọn nhà thầu",
    link:"https://vanban.chinhphu.vn/?pageid=27160&docid=214821"
  },
  {
    id:"21",
    category:"Xây dựng",
    sokyhieu:"37/2015/NĐ-CP",
    ngaybanhanh:"22/4/2015",
    ngayhieuluc:"15/6/2015",
    loaivanban:"Nghị định",
    coquanbanhanh:"Chính phủ",
    nguoiky:"Nguyễn Tấn Dũng",
    trichyeu:"quy định chi tiết về hợp đồng xây dựng",
    link:"https://vanban.chinhphu.vn/?pageid=27160&docid=179655"
  },
  {
    id:"22",
    category:"Xây dựng",
    sokyhieu:"50/2021/NĐ-CP",
    ngaybanhanh:"01/4/2021",
    ngayhieuluc:"01/4/2021",
    loaivanban:"Nghị định",
    coquanbanhanh:"Chính phủ",
    nguoiky:"Nguyễn Xuân Phúc",
    trichyeu:"sửa đổi, bổ sung một số điều của Nghị định số 37/2015/NĐ-CP ngày 22 tháng 4 năm 2015 của Chính phủ quy định chi tiết về hợp đồng xây dựng",
    link:"https://vanban.chinhphu.vn/?pageid=27160&docid=202990"
  },
  {
    id:"23",
    category:"Tài chính",
    sokyhieu:"17/2025/NĐ-CP",
    ngaybanhanh:"06/02/2025",
    ngayhieuluc:"06/02/2025",
    loaivanban:"Nghị định",
    coquanbanhanh:"Chính phủ",
    nguoiky:"Trần Hồng Hà",
    trichyeu:"sửa đổi, bổ sung một số điều của các Nghị định quy định chi tiết một số điều và biện pháp thi hành Luật Đấu thầu",
    link:"https://vanban.chinhphu.vn/?pageid=27160&docid=212658"
  },
  {
    id:"24",
    category:"Xây dựng",
    sokyhieu:"35/2023/NĐ-CP",
    ngaybanhanh:"20/6/2023",
    ngayhieuluc:"20/6/2023",
    loaivanban:"Nghị định",
    coquanbanhanh:"Chính phủ",
    nguoiky:"Trần Hồng Hà",
    trichyeu:"sửa đổi, bổ sung một số điều của các Nghị định thuộc lĩnh vực quản lý nhà nước của Bộ Xây dựng",
    link:"https://vanban.chinhphu.vn/?pageid=27160&docid=208090"
  },
  {
    id:"25",
    category:"Đất đai - Nhà ở",
    sokyhieu:"95/2024/NĐ-CP",
    ngaybanhanh:"24/7/2024",
    ngayhieuluc:"01/8/2024",
    loaivanban:"Nghị định",
    coquanbanhanh:"Chính phủ",
    nguoiky:"Trần Hồng Hà",
    trichyeu:"quy định chi tiết một số điều của Luật Nhà ở",
    link:"https://vanban.chinhphu.vn/?pageid=27160&docid=210761"
  },
  {
    id:"26",
    category:"Xây dựng",
    sokyhieu:"15/2021/NĐ-CP",
    ngaybanhanh:"03/3/2021",
    ngayhieuluc:"03/3/2021",
    loaivanban:"Nghị định",
    coquanbanhanh:"Chính phủ",
    nguoiky:"Nguyễn Xuân Phúc",
    trichyeu:"quy định chi tiết một số nội dung về quản lý dự án đầu tư xây dựng",
    link:"https://vanban.chinhphu.vn/?pageid=27160&docid=202756"
  },
  {
    id:"27",
    category:"Xây dựng",
    sokyhieu:"697/QĐ-UBND",
    ngaybanhanh:"30/01/2026",
    ngayhieuluc:"30/01/2026",
    loaivanban:"Quyết định",
    coquanbanhanh:"Ủy ban nhân dân Thành phố Hồ Chí Minh",
    nguoiky:"",
    trichyeu:"về việc tổ chức lại Trung tâm Quản lý nhà và Giám định xây dựng trực thuộc Sở Xây dựng",
    link:""
  },
  {
    id:"28",
    category:"Xây dựng",
    sokyhieu:"828/QĐ-SXD-TCCB",
    ngaybanhanh:"17/3/2026",
    ngayhieuluc:"17/3/2026",
    loaivanban:"Quyết định",
    coquanbanhanh:"Sở Xây dựng",
    nguoiky:"",
    trichyeu:"ban hành Quy định chức năng, nhiệm vụ, quyền hạn và cơ cấu tổ chức của Trung tâm Quản lý nhà và Giám định xây dựng trực thuộc Sở Xây dựng Thanh phố Hồ Chí Minh",
    link:""
  },
  {
    id:"29",
    category:"Xây dựng",
    sokyhieu:"2308/QĐ-SXD-TC",
    ngaybanhanh:"22/12/2025",
    ngayhieuluc:"22/12/2025",
    loaivanban:"Quyết định",
    coquanbanhanh:"Sở Xây dựng",
    nguoiky:"",
    trichyeu:"về việc giao dự toán ngân sách Nhà nước năm 2026",
    link:""
  },
  {
    id:"30",
    category:"Xây dựng",
    sokyhieu:"776/QĐ-SXD-TC",
    ngaybanhanh:"05/3/2026",
    ngayhieuluc:"05/3/2026",
    loaivanban:"Quyết định",
    coquanbanhanh:"Sở Xây dựng",
    nguoiky:"",
    trichyeu:"về việc giao dự toán ngân sách nhà nước năm 2026 (điều chỉnh lần 2)",
    link:""
  },
  {
    id:"31",
    category:"Xây dựng",
    sokyhieu:"1454/QĐ-SXD-TC",
    ngaybanhanh:"08/5/2026",
    ngayhieuluc:"08/5/2026",
    loaivanban:"Quyết định",
    coquanbanhanh:"Sở Xây dựng",
    nguoiky:"",
    trichyeu:"về việc giao dự toán ngân sách nhà nước năm 2026 (điều chỉnh lần 4)",
    link:""
  },
  {
    id:"32",
    category:"Tài chính",
    sokyhieu:"004/2025/TT-BNV",
    ngaybanhanh:"07/5/2025",
    ngayhieuluc:"01/7/2025",
    loaivanban:"Thông tư",
    coquanbanhanh:"Bộ Nội vụ",
    nguoiky:"Nguyễn Mạnh Khương",
    trichyeu:"quy định mức lương của chuyên gia tư vấn trong nước làm cơ sở cho việc xác định giá gói thầu",
    link:"https://chinhphu.vn/?pageid=27160&docid=213678&classid=1"
  },
  {
    id:"33",
    category:"Xây dựng",
    sokyhieu:"01/2025/TT-BXD",
    ngaybanhanh:"22/01/2025",
    ngayhieuluc:"08/3/2025",
    loaivanban:"Thông tư",
    coquanbanhanh:"Bộ Xây dựng",
    nguoiky:"Bùi Xuân Dũng",
    trichyeu:"sửa đổi, bổ sung một số điều của Thông tư số 13/2021/TT-BXD ngày 31 tháng 8 năm 2021 của Bộ trưởng Bộ Xây dựng hướng dẫn phương pháp xác định các chỉ tiêu kinh tế kỹ thuật và đo bóc khối lượng công trình, Thông tư số 11/2021/TT-BXD ngày 31 tháng 8 năm 2021 của Bộ trưởng Bộ Xây dựng hướng dẫn một số nội dung xác định và quản lý chi phí đầu tư xây dựng đã được sửa đổi, bổ sung một số điều tại Thông tư số 14/2023/TT-BXD ngày 29 tháng 12 năm 2023 của Bộ trưởng Bộ Xây dựng",
    link:"https://chinhphu.vn/?pageid=27160&docid=212647"
  },
  {
    id:"34",
    category:"Xây dựng",
    sokyhieu:"02/2023/TT-BXD",
    ngaybanhanh:"03/3/2023",
    ngayhieuluc:"20/4/2023",
    loaivanban:"Thông tư",
    coquanbanhanh:"Bộ Xây dựng",
    nguoiky:"Bùi Hồng Minh",
    trichyeu:"hướng dẫn một số nội dung về hợp đồng xây dựng",
    link:"https://vanban.chinhphu.vn/?pageid=27160&docid=207653"
  },
  {
    id:"35",
    category:"Xây dựng",
    sokyhieu:"02/2025/TT-BXD",
    ngaybanhanh:"31/3/2025",
    ngayhieuluc:"20/5/2025",
    loaivanban:"Thông tư",
    coquanbanhanh:"Bộ Xây dựng",
    nguoiky:"Phạm Minh Hà",
    trichyeu:"sửa đổi, bổ sung một số điều của Thông tư số 06/2021/TT-BXD ngày 30 tháng 6 năm 2021 của Bộ trưởng Bộ Xây dựng quy định về phân cấp công trình xây dựng và hướng dẫn áp dụng trong quản lý hoạt động đầu tư xây dựng",
    link:"https://chinhphu.vn/?pageid=27160&docid=213328&classid=1"
  },
  {
    id:"36",
    category:"Xây dựng",
    sokyhieu:"08/2025/TT-BXD",
    ngaybanhanh:"30/5/2025",
    ngayhieuluc:"15/7/2025",
    loaivanban:"Thông tư",
    coquanbanhanh:"Bộ Xây dựng",
    nguoiky:"Bùi Xuân Dũng",
    trichyeu:"sửa đổi, bổ sung một số định mức xây dựng ban hành tại Thông tư số 12/2021/TT-BXD ngày 31 tháng 8 năm 2021 của Bộ trưởng Bộ Xây dựng",
    link:"https://chinhphu.vn/?pageid=27160&docid=213852&classid=1"
  },
  {
    id:"37",
    category:"Xây dựng",
    sokyhieu:"11/2021/TT-BXD",
    ngaybanhanh:"31/8/2021",
    ngayhieuluc:"15/10/2021",
    loaivanban:"Thông tư",
    coquanbanhanh:"Bộ Xây dựng",
    nguoiky:"Bùi Hồng Minh",
    trichyeu:"hướng dẫn một số nội dung xác định và quản lý chi phí đầu tư xây dựng",
    link:"https://congbao.chinhphu.vn/van-ban/thong-tu-so-11-2021-tt-bxd-34379.htm"
  },
  {
    id:"38",
    category:"Xây dựng",
    sokyhieu:"12/2021/TT-BXD",
    ngaybanhanh:"31/8/2021",
    ngayhieuluc:"15/10/2021",
    loaivanban:"Thông tư",
    coquanbanhanh:"Bộ Xây dựng",
    nguoiky:"Bùi Hồng Minh",
    trichyeu:"ban hành định mức xây dựng",
    link:"https://congbao.chinhphu.vn/van-ban/thong-tu-so-12-2021-tt-bxd-34408/37030.htm"
  },
  {
    id:"39",
    category:"Xây dựng",
    sokyhieu:"14/2021/TT-BXD",
    ngaybanhanh:"08/9/2021",
    ngayhieuluc:"01/11/2021",
    loaivanban:"Thông tư",
    coquanbanhanh:"Bộ Xây dựng",
    nguoiky:"Lê Quang Hùng",
    trichyeu:"hướng dẫn xác định chi phí bảo trì công trình xây dựng",
    link:"https://vanban.chinhphu.vn/?pageid=27160&docid=204048"
  },
  {
    id:"40",
    category:"Tài chính",
    sokyhieu:"50/2022/TT-BTC",
    ngaybanhanh:"11/8/2022",
    ngayhieuluc:"01/10/2022",
    loaivanban:"Thông tư",
    coquanbanhanh:"Bộ Tài chính",
    nguoiky:"Nguyễn Đức Chi",
    trichyeu:"hướng dẫn thực hiện một số điều của Nghị định số 119/2015/NĐ-CP ngày 13 tháng 11 năm 2015 của Chính phủ quy định bảo hiểm bắt buộc trong hoạt động đầu tư xây dựng và Nghị định số 20/2022/NĐ-CP ngày 10 tháng 3 năm 2022 sửa đổi, bổ sung một số điều của Nghị định số 119/2015/NĐ-CP ngày 13 tháng 11 năm 2015 của Chính phủ quy định bảo hiểm bắt buộc trong hoạt động đầu tư xây dựng",
    link:"https://vanban.chinhphu.vn/?pageid=27160&docid=206463"
  },
  {
    id:"41",
    category:"Xây dựng",
    sokyhieu:"60/2025/TT-BXD",
    ngaybanhanh:"30/12/2025",
    ngayhieuluc:"15/02/2026",
    loaivanban:"Thông tư",
    coquanbanhanh:"Bộ Xây dựng",
    nguoiky:"Bùi Xuân Dũng",
    trichyeu:"sửa đổi, bổ sung một số nội dung các Thông tư số 11/2021/TT-BXD ngày 31 tháng 8 năm 2021 của Bộ trưởng Bộ Xây dựng hướng dẫn một số nội dung xác định và quản lý chi phí đầu tư xây dựng; Thông tư số 12/2021/TT-BXD ngày 31 tháng 8 năm 2021 của Bộ trưởng Bộ Xây dựng ban hành định mức xây dựng; Thông tư số 13/2021/TT-BXD ngày 31 tháng 8 năm 2021 của Bộ trưởng Bộ Xây dựng hướng dẫn phương pháp xác định các chỉ tiêu kinh tế kỹ thuật và đo bóc khối lượng công trình và Thông tư số 14/2021/TT-BXD ngày 08 tháng 9 năm 2021 của Bộ trưởng Bộ Xây dựng hướng dẫn xác định chi phí bảo trì công trình xây dựng",
    link:"https://vanban.chinhphu.vn/?pageid=27160&docid=216436"
  },
  {
    id:"42",
    category:"Tài chính",
    sokyhieu:"79/2025/TT-BTC",
    ngaybanhanh:"04/8/2025",
    ngayhieuluc:"04/8/2025",
    loaivanban:"Thông tư",
    coquanbanhanh:"Bộ Tài chính",
    nguoiky:"Nguyễn Đức Tâm",
    trichyeu:"hướng dẫn việc cung cấp, đăng tải thông tin về đấu thầu và mẫu hồ sơ đấu thầu trên Hệ thống mạng đấu thầu quốc gia",
    link:"https://vanban.chinhphu.vn/?pageid=27160&docid=214844&classid=1"
  },
  {
    id:"43",
    category:"Xây dựng",
    sokyhieu:"13/2021/TT-BXD",
    ngaybanhanh:"31/8/2021",
    ngayhieuluc:"15/10/2021",
    loaivanban:"Thông tư",
    coquanbanhanh:"Bộ Xây dựng",
    nguoiky:"Bùi Hồng Minh",
    trichyeu:"hướng dẫn phương pháp xác định các chỉ tiêu kinh tế kỹ thuật và đo bóc khối lượng công trình",
    link:"https://congbao.chinhphu.vn/van-ban/thong-tu-so-13-2021-tt-bxd-34356/36900.htm"
  },
  {
    id:"44",
    category:"Xây dựng",
    sokyhieu:"3385/QĐ-UBND",
    ngaybanhanh:"23/12/2025",
    ngayhieuluc:"23/12/2025",
    loaivanban:"Quyết định",
    coquanbanhanh:"Ủy ban nhân dân Thành phố Hồ Chí Minh",
    nguoiky:"",
    trichyeu:"về ủy quyền cho người đứng đầu cơ quan chuyên môn, tổ chức hành chính khác, đơn vị sự nghiệp công lập thuộc Ủy ban nhân dân Thành phố (là đơn vị dự toán cấp I) quyết định đầu tư xây dựng các dự án sửa chữa, cải tạo, nâng cấp mở rộng, xây dựng mới hạng mục công trình của đơn vị và các đơn vị do mình quản lý có dự toán kinh phí thực hiện từ 500 triệu đồng trở lên đến 20 tỷ đồng sử dụng nguồn vốn chi thường xuyên ngân sách nhà nước",
    link:""
  },
  {
    id:"45",
    category:"Xây dựng",
    sokyhieu:"1813/QĐ-UBND",
    ngaybanhanh:"30/3/2026",
    ngayhieuluc:"30/3/2026",
    loaivanban:"Quyết định",
    coquanbanhanh:"Ủy ban nhân dân Thành phố Hồ Chí Minh",
    nguoiky:"Hoàng Nguyên Dinh",
    trichyeu:"phê duyệt Kế hoạch bảo trì công trình thuộc tài sản công giao Trung tâm Quản lý nhà và Giám định xây dựng quản lý năm 2026",
    link:""
  },
  {
    id:"46",
    category:"Vĩnh Lộc B",
    sokyhieu:"3194/UBND-ĐT",
    ngaybanhanh:"24/10/2025",
    ngayhieuluc:"24/10/2025",
    loaivanban:"Công văn",
    coquanbanhanh:"Ủy ban nhân dân Thành phố Hồ Chí Minh",
    nguoiky:"Bùi Xuân Cường",
    trichyeu:"về chuẩn bị nguồn nhà ở phục vụ tái định cư cho các dự án BOT và dự án xây dựng cầu đường Bình Tiên",
    link:""
  },
  {
    id:"47",
    category:"Vĩnh Lộc B",
    sokyhieu:"5252/UBND-ĐT",
    ngaybanhanh:"31/12/2025",
    ngayhieuluc:"31/12/2025",
    loaivanban:"Công văn",
    coquanbanhanh:"Ủy ban nhân dân Thành phố Hồ Chí Minh",
    nguoiky:"Hoàng Nguyên Dinh",
    trichyeu:"về bố trí nhà ở, nền đất tái định cư phục vụ các dự án trên địa bàn xã Hưng Long, xã Tân Nhựt, xã Bình Hưng",
    link:""
  },
  {
    id:"48",
    category:"Vĩnh Lộc B",
    sokyhieu:"788/SXD-QLN&TTBĐS",
    ngaybanhanh:"09/01/2026",
    ngayhieuluc:"09/01/2026",
    loaivanban:"Công văn",
    coquanbanhanh:"Sở Xây dựng",
    nguoiky:"Trần Sĩ Nam",
    trichyeu:"thông báo vị trí căn hộ, nền đất phục vụ tái định cư cho Dự án cải tạo, nâng cấp Quốc lộ 22 theo Công văn số 3194/UBND-ĐT ngày 24 tháng 10 năm 2025 của Ủy ban nhân dân Thành phố",
    link:""
  },
  {
    id:"49",
    category:"Vĩnh Lộc B",
    sokyhieu:"6057/SXD-QLN&TTBĐS",
    ngaybanhanh:"13/02/2026",
    ngayhieuluc:"13/02/2026",
    loaivanban:"Công văn",
    coquanbanhanh:"Sở Xây dựng",
    nguoiky:"Trần Sĩ Nam",
    trichyeu:"thông báo vị trí căn hộ, nền đất phục vụ tái định cư cho các dự án trên địa bàn xã Hưng Long, xã Tân Nhựt, xã Bình Hưng theo Công văn số 5252/UBND-ĐT ngày 31 tháng 12 năm 2025 của Ủy ban nhân dân Thành phố",
    link:""
  },
  {
    id:"50",
    category:"Vĩnh Lộc B",
    sokyhieu:"182/UBND-KT",
    ngaybanhanh:"31/7/2025",
    ngayhieuluc:"31/7/2025",
    loaivanban:"Công văn",
    coquanbanhanh:"Ủy ban nhân dân xã Nhà Bè",
    nguoiky:"Trần Minh Hiến",
    trichyeu:"về sửa chữa căn hộ tại các chung cư thuộc tài sản công do Trung tâm Quản lý nhà và Giám định xây dựng đang quản lý",
    link:""
  },
  {
    id:"51",
    category:"Vĩnh Lộc B",
    sokyhieu:"974/UBND",
    ngaybanhanh:"29/10/2025",
    ngayhieuluc:"29/10/2025",
    loaivanban:"Công văn",
    coquanbanhanh:"Ủy ban nhân dân xã Tân Nhựt",
    nguoiky:"Phạm Nhật Trường",
    trichyeu:"về sửa chữa căn hộ tại các chung cư thuộc tài sản công do Trung tâm Quản lý nhà và Giám định xây dựng đang quản lý, xã Tân Nhựt, Thành phố  Hồ Chí Minh",
    link:""
  },
  {
    id:"52",
    category:"Vĩnh Lộc B",
    sokyhieu:"1668/QĐ-SXD-QLXDCT",
    ngaybanhanh:"05/6/2026",
    ngayhieuluc:"05/6/2026",
    loaivanban:"Quyết định",
    coquanbanhanh:"Sở Xây dựng",
    nguoiky:"",
    trichyeu:"về việc phê duyệt dự án “Sửa chữa các căn hộ tại khu dân cư Vĩnh Lộc B (30ha), xã Tân Vĩnh Lộc, Thành phố Hồ Chí Minh”",
    link:""
  },
  {
    id:"53",
    category:"Xây dựng",
    sokyhieu:"1036/QĐ-TTQLNGĐXD-TCHC",
    ngaybanhanh:"27/02/2026",
    ngayhieuluc:"27/02/2026",
    loaivanban:"Quyết định",
    coquanbanhanh:"Trung tâm Quản lý nhà và Giám định xây dựng",
    nguoiky:"",
    trichyeu:"về việc ủy quyền cho ông Vũ Đặng Dũng - Phó Giám đốc Trung tâm Quản lý nhà và Giám định xây dựng",
    link:""
  },
  {
    id:"54",
    category:"Vĩnh Lộc B",
    sokyhieu:"3438/QĐ-TTQLNGĐXD-TVXD",
    ngaybanhanh:"24/4/2026",
    ngayhieuluc:"24/4/2026",
    loaivanban:"Quyết định",
    coquanbanhanh:"Trung tâm Quản lý nhà và Giám định xây dựng",
    nguoiky:"Vũ Đặng Dũng",
    trichyeu:"về việc phê duyệt Dự toán và Kế hoạch lựa chọn nhà thầu giai đoạn chuẩn bị đầu tư dự án thuộc dự toán mua sắm “Sửa chữa các căn hộ tại khu dân cư Vĩnh Lộc B (30ha), xã Tân Vĩnh Lộc, Thành phố Hồ Chí Minh”",
    link:""
  },
  {
    id:"55",
    category:"Vĩnh Lộc B",
    sokyhieu:"4151/QĐ-TTQLNGĐXD-TVXD",
    ngaybanhanh:"12/5/2026",
    ngayhieuluc:"12/5/2026",
    loaivanban:"Quyết định",
    coquanbanhanh:"Trung tâm Quản lý nhà và Giám định xây dựng",
    nguoiky:"Vũ Đặng Dũng",
    trichyeu:"về việc phê duyệt kết quả chỉ định thầu, gói thầu tư vấn 1: Tư vấn lập Báo cáo kinh tế - kỹ thuật dự án “Sửa chữa các căn hộ tại khu dân cư Vĩnh Lộc B (30ha), xã Tân Vĩnh Lộc, Thành phố Hồ Chí Minh”",
    link:""
  },
  {
    id:"56",
    category:"Vĩnh Lộc B",
    sokyhieu:"4152/QĐ-TTQLNGĐXD-TVXD",
    ngaybanhanh:"12/5/2026",
    ngayhieuluc:"12/5/2026",
    loaivanban:"Quyết định",
    coquanbanhanh:"Trung tâm Quản lý nhà và Giám định xây dựng",
    nguoiky:"Vũ Đặng Dũng",
    trichyeu:"về việc phê duyệt kết quả chỉ định thầu, gói thầu tư vấn 2: Tư vấn thẩm tra Báo cáo kinh tế - kỹ thuật dự án “Sửa chữa các căn hộ tại khu dân cư Vĩnh Lộc B (30ha), xã Tân Vĩnh Lộc, Thành phố Hồ Chí Minh”",
    link:""
  }    
    // ... Thêm các văn bản khác tương tự ...
];

export default lawData;